name: MCEngineParty
version: ${version}
main: io.github.mcengine.spigotmc.party.engine.MCEnginePartySpigotMC
author: MCEngine
description: MCEngine Party
api-version: 1.13

commands:
  party:
    description: Main party command
    usage: /party <create|invite|kick|leave>
    aliases: []
