enable: false

# Database support
# - sqlite
# - mysql
# - postgresql
database:
  type: sqlite

  sqlite:
    path: party.db

  mysql:
    host: localhost
    port: "3306"
    name: mcengine
    user: root
    password: ""

  postgresql:
    host: localhost
    port: "5432"
    name: mcengine
    user: postgres
    password: ""

  mongodb:
    uri: mongodb://localhost:27017
    name: mcengine
    collection: party
